import {
  Megaphone,
  Handshake,
  Presentation,
  Mail,
  Share2,
  Search,
  Building2,
  Users,
  Zap,
  PenTool,
  Headphones,
  ShoppingCart,
} from "lucide-react";

export const CATEGORIES = [
  { id: "marketing", name: "Marketing", icon: Megaphone, count: "80+", href: "#" },
  { id: "sales", name: "Sales", icon: Handshake, count: "75+", href: "#" },
  { id: "presentations", name: "Presentations", icon: Presentation, count: "60+", href: "#" },
  { id: "email", name: "Email", icon: Mail, count: "90+", href: "#" },
  { id: "social", name: "Social Media", icon: Share2, count: "100+", href: "#" },
  { id: "seo", name: "SEO & Content", icon: Search, count: "70+", href: "#" },
  { id: "business", name: "Business", icon: Building2, count: "65+", href: "#" },
  { id: "hr", name: "HR & Recruiting", icon: Users, count: "55+", href: "#" },
  { id: "productivity", name: "Productivity", icon: Zap, count: "80+", href: "#" },
  { id: "creative", name: "Creative Writing", icon: PenTool, count: "70+", href: "#" },
  { id: "customer-service", name: "Customer Service", icon: Headphones, count: "50+", href: "#" },
  { id: "e-commerce", name: "E-Commerce", icon: ShoppingCart, count: "40+", href: "#" },
];

export const PROMPTS = [
  { id: 1, category: "Marketing", title: "Full-funnel marketing strategy for product", text: "Write a full-funnel marketing strategy for [product] targeting [audience]. Include awareness, nurturing, and conversion tactics.", industry: "Universal"},
  { id: 2, category: "Marketing", title: "Unique value propositions for brand", text: "Create 10 unique value propositions for [brand] that speak directly to [target persona].", industry: "Universal"},
  { id: 3, category: "Marketing", title: "Compelling product launch announcement", text: "Write a compelling product launch announcement for [product] with a hook, key benefits, social proof, and a clear CTA.", industry: "Universal"},
  { id: 4, category: "Marketing", title: "30-day content calendar for brand", text: "Generate a 30-day content calendar for [brand] on [platform]. Include topics, formats, and CTAs.", industry: "Universal"},
  { id: 5, category: "Marketing", title: "A/B test variants", text: "Write 5 A/B test variants for a Google Ads headline promoting [product]. Each under 30 characters.", industry: "Universal"},
  { id: 6, category: "Marketing", title: "Competitor analysis for brand", text: "Create a competitor analysis for [brand] vs. top 3 competitors. Focus on positioning, pricing, and messaging gaps.", industry: "Universal"},
  { id: 7, category: "Marketing", title: "Landing page for product", text: "Write a landing page for [product]. Include a headline, three benefit sections, social proof block, and FAQ.", industry: "Universal"},
  { id: 8, category: "Marketing", title: "Brand voice guide for company", text: "Develop a brand voice guide for [company]. Define tone, banned words, audience, and 5 on-brand writing examples.", industry: "Universal"},
  { id: 9, category: "Marketing", title: "Press release announcing news", text: "Write a press release announcing [news] for [company]. Include a quote from leadership and a boilerplate.", industry: "Universal"},
  { id: 10, category: "Marketing", title: "Referral program concept for brand", text: "Create a referral program concept for [brand]. Include incentives, messaging, and a step-by-step user flow.", industry: "Universal"},
  { id: 11, category: "Marketing", title: "Ad copy variants for Meta", text: "Write 10 ad copy variants for Meta Ads promoting [product]. Each under 125 characters. Test 3 different angles.", industry: "Universal"},
  { id: 12, category: "Marketing", title: "Go-to-market strategy for product launching", text: "Draft a go-to-market strategy for [product] launching in [market]. Include launch phases, channels, and KPIs.", industry: "Universal"},
  { id: 13, category: "Sales", title: "Personalized cold outreach email", text: "Write a personalized cold outreach email to [prospect] at [company]. Under 100 words. End with a soft CTA.", industry: "Universal"},
  { id: 14, category: "Sales", title: "Objection responses", text: "Create 3 objection responses for: 'We don't have the budget right now.' Keep the conversation open.", industry: "Universal"},
  { id: 15, category: "Sales", title: "3-part follow-up sequence", text: "Write a 3-part follow-up sequence for a prospect who went silent after a demo. Space 3 days apart.", industry: "Universal"},
  { id: 16, category: "Sales", title: "Qualifying questions for a job", text: "Generate 10 qualifying questions for a [job title] in [industry] to assess fit for [product].", industry: "Universal"},
  { id: 17, category: "Sales", title: "2-minute elevator pitch for product", text: "Write a 2-minute elevator pitch for [product]. State the problem, solution, and ideal customer. No jargon.", industry: "Universal"},
  { id: 18, category: "Sales", title: "Competitive battlecard", text: "Create a competitive battlecard: [our product] vs [competitor]. Include where we win, where they win, and 3 killer questions.", industry: "Universal"},
  { id: 19, category: "Sales", title: "LinkedIn connection request message", text: "Write a LinkedIn connection request message to [prospect]. Mention a mutual connection or relevant trigger event.", industry: "Universal"},
  { id: 20, category: "Sales", title: "Contract renewal email", text: "Draft a contract renewal email for an existing customer whose subscription expires in 30 days.", industry: "Universal"},
  { id: 21, category: "Sales", title: "Sales one-pager for product", text: "Create a sales one-pager for [product]. Include: problem, solution, 3 benefits, pricing tiers, and next steps.", industry: "Universal"},
  { id: 22, category: "Sales", title: "Proposal introduction for a service", text: "Write a proposal introduction for a [service] project worth [amount] for [client]. Professional and confident.", industry: "Universal"},
  { id: 23, category: "Sales", title: "'breaking up' email", text: "Draft a 'breaking up' email to a prospect who hasn't responded in 6 weeks. Friendly, no pressure.", industry: "Universal"},
  { id: 24, category: "Sales", title: "Post-demo follow-up email summarizing key", text: "Write a post-demo follow-up email summarizing key takeaways and next steps. Attach a relevant case study.", industry: "Universal"},
  { id: 25, category: "Presentations", title: "10-slide outline for topic targeting", text: "Create a 10-slide outline for [topic] targeting [audience]. Include slide title, 3 bullets, and visual suggestion per slide.", industry: "Universal"},
  { id: 26, category: "Presentations", title: "Speaker notes for a slide", text: "Write speaker notes for a slide titled '[slide title]' in a talk about [topic]. 150–200 words, conversational.", industry: "Universal"},
  { id: 27, category: "Presentations", title: "Data into 3 memorable insights", text: "Turn this data into 3 memorable insights for a slide: [paste data]. Format as: stat + what it means.", industry: "Universal"},
  { id: 28, category: "Presentations", title: "100-word opening story", text: "Write a 100-word opening story for a presentation on [topic] that hooks [audience] immediately.", industry: "Universal"},
  { id: 29, category: "Presentations", title: "Content for a 5-minute presentation", text: "Rewrite this content for a 5-minute presentation slot: [paste content]. Keep only the highest-impact points.", industry: "Universal"},
  { id: 30, category: "Presentations", title: "Pitch deck outline", text: "Create a pitch deck outline for a startup in [industry] seeking [amount]. Include all 7 standard investor sections.", industry: "Universal"},
  { id: 31, category: "Presentations", title: "Possible closing statements", text: "Write 3 possible closing statements for a presentation on [topic]. Each should inspire action or reflection.", industry: "Universal"},
  { id: 32, category: "Presentations", title: "Data visualization types for this", text: "Suggest 5 data visualization types for this dataset: [describe data]. Explain why each works for this audience.", industry: "Universal"},
  { id: 33, category: "Presentations", title: "Dense bullet points as short,", text: "Rewrite these 5 dense bullet points as short, punchy slide headlines: [paste bullets].", industry: "Universal"},
  { id: 34, category: "Presentations", title: "Q&A prep sheet", text: "Write a Q&A prep sheet for a presentation on [topic]. Include 10 tough questions and model answers.", industry: "Universal"},
  { id: 35, category: "Email", title: "Professional email requesting action from", text: "Write a professional email requesting [action] from [recipient]. Concise, clear deadline and next step.", industry: "Universal"},
  { id: 36, category: "Email", title: "Email to be half as", text: "Rewrite this email to be half as long without losing the core message: [paste email].", industry: "Universal"},
  { id: 37, category: "Email", title: "Newsletter email announcing news", text: "Write a newsletter email announcing [news]. Include subject line, preview text, hook, 150-word body, and CTA.", industry: "Universal"},
  { id: 38, category: "Email", title: "Subject line options", text: "Create 5 subject line options for an email about [topic]. Mix urgency, curiosity, and benefit-driven angles.", industry: "Universal"},
  { id: 39, category: "Email", title: "Polite but firm email declining", text: "Write a polite but firm email declining [request]. Preserve the relationship. Offer an alternative.", industry: "Universal"},
  { id: 40, category: "Email", title: "Re-engagement email for subscribers inactive", text: "Draft a re-engagement email for subscribers inactive 90 days. Add something valuable. Easy unsubscribe line.", industry: "Universal"},
  { id: 41, category: "Email", title: "Onboarding welcome email sequence (3", text: "Write an onboarding welcome email sequence (3 emails) for new users of [product]. Space 2 days apart.", industry: "Universal"},
  { id: 42, category: "Email", title: "Apology email to customer", text: "Draft an apology email to [customer] for [issue]. Acknowledge, explain, resolve, and retain trust.", industry: "Universal"},
  { id: 43, category: "Email", title: "Internal announcement email about change/news", text: "Write an internal announcement email about [change/news] for [company]. Clear, reassuring tone.", industry: "Universal"},
  { id: 44, category: "Email", title: "Automated cart abandonment email", text: "Create an automated cart abandonment email for [ecommerce brand]. Urgency without pressure. Include discount option.", industry: "Universal"},
  { id: 45, category: "Email", title: "Collaboration proposal email to brand/person", text: "Write a collaboration proposal email to [brand/person] about [idea]. 120 words max. End with a call.", industry: "Universal"},
  { id: 46, category: "Email", title: "Post-event thank you email", text: "Draft a post-event thank you email to attendees of [event]. Include key takeaways and a next step resource.", industry: "Universal"},
  { id: 47, category: "Social Media", title: "LinkedIn post about topic/achievement", text: "Write a LinkedIn post about [topic/achievement]. Strong opening hook. Include a personal insight. End with a question.", industry: "Universal"},
  { id: 48, category: "Social Media", title: "Instagram caption options for describe", text: "Create 5 Instagram caption options for [describe photo]. Brand voice: [tone]. 8–10 hashtags. One storytelling format.", industry: "Universal"},
  { id: 49, category: "Social Media", title: "8-tweet Twitter/X thread breaking down", text: "Write an 8-tweet Twitter/X thread breaking down [topic] for [audience]. Hook tweet + insights + final CTA.", industry: "Universal"},
  { id: 50, category: "Social Media", title: "60-second TikTok script for brand", text: "Generate a 60-second TikTok script for [brand] about [topic]. Include on-screen text, hook, and spoken script.", industry: "Universal"},
  { id: 51, category: "Social Media", title: "Weekly social media plan", text: "Create a weekly social media plan for [brand] across LinkedIn, Instagram, and X. Content pillars + formats.", industry: "Universal"},
  { id: 52, category: "Social Media", title: "Repurpose this blog post into", text: "Repurpose this blog post into 5 social formats: LinkedIn post, tweet, Instagram carousel, YouTube Short, quote graphic.", industry: "Universal"},
  { id: 53, category: "Social Media", title: "Viral hook ideas for LinkedIn", text: "Write 10 viral hook ideas for LinkedIn posts in the [industry] space. No cringe. No fake urgency.", industry: "Universal"},
  { id: 54, category: "Social Media", title: "Pinterest pin descriptions for product/topic", text: "Generate 5 Pinterest pin descriptions for [product/topic]. SEO-friendly. Include a CTA in each.", industry: "Universal"},
  { id: 55, category: "Social Media", title: "YouTube video description", text: "Write a YouTube video description for a video titled '[title]'. Include timestamps, keywords, and CTA links.", industry: "Universal"},
  { id: 56, category: "Social Media", title: "Instagram Reel concepts for brand", text: "Create 3 Instagram Reel concepts for [brand]. Include the hook, content structure, and caption for each.", industry: "Universal"},
  { id: 57, category: "Social Media", title: "Community post for brand's Facebook", text: "Write a community post for [brand]'s Facebook Group to spark engagement around [topic]. Include a poll or prompt.", industry: "Universal"},
  { id: 58, category: "Social Media", title: "LinkedIn article headline options", text: "Draft 5 LinkedIn article headline options for a piece about [topic]. Make them specific and curiosity-driven.", industry: "Universal"},
  { id: 59, category: "SEO & Content", title: "2,000-word SEO blog post", text: "Write a 2,000-word SEO blog post on '[topic]' targeting keyword '[keyword]'. Include H2s, H3s, FAQ, and CTA.", industry: "Universal"},
  { id: 60, category: "SEO & Content", title: "Long-tail keyword ideas for niche", text: "Generate 20 long-tail keyword ideas for [niche]. Table format: keyword, intent (informational/commercial), difficulty.", industry: "Universal"},
  { id: 61, category: "SEO & Content", title: "Meta title (max 60 chars)", text: "Write a meta title (max 60 chars) and meta description (max 155 chars) for a page about [topic] targeting [keyword].", industry: "Universal"},
  { id: 62, category: "SEO & Content", title: "Improve this blog intro", text: "Improve this blog intro to hook the reader in 3 sentences with keyword '[keyword]': [paste intro].", industry: "Universal"},
  { id: 63, category: "SEO & Content", title: "Content cluster plan around 'pillar", text: "Create a content cluster plan around '[pillar topic]'. 1 pillar page + 8 cluster pages with titles and keywords.", industry: "Universal"},
  { id: 64, category: "SEO & Content", title: "FAQ questions and answers", text: "Write 10 FAQ questions and answers for [topic]. Optimized for Google Featured Snippets. 2–3 sentences each.", industry: "Universal"},
  { id: 65, category: "SEO & Content", title: "Paragraph to naturally include 'keyword'", text: "Rewrite this paragraph to naturally include '[keyword]' twice without sounding forced: [paste paragraph].", industry: "Universal"},
  { id: 66, category: "SEO & Content", title: "Product description for product (150", text: "Write a product description for [product] (150 words). SEO-optimized, benefit-first, and scannable.", industry: "Universal"},
  { id: 67, category: "SEO & Content", title: "Internal linking strategy", text: "Create an internal linking strategy for a blog in the [niche] space. Identify 5 hub pages and 10 spoke pages.", industry: "Universal"},
  { id: 68, category: "SEO & Content", title: "Guest post pitch email", text: "Write a guest post pitch email to [site] about '[proposed topic]'. Explain why it serves their audience.", industry: "Universal"},
  { id: 69, category: "Business", title: "SWOT analysis for company", text: "Conduct a SWOT analysis for [company] in the [industry] market. 4–5 points per quadrant + one strategic action.", industry: "Universal"},
  { id: 70, category: "Business", title: "One-page business case for initiative", text: "Write a one-page business case for [initiative] targeting [decision maker]. Include ROI, risks, and next steps.", industry: "Universal"},
  { id: 71, category: "Business", title: "60-minute meeting agenda for meeting", text: "Create a 60-minute meeting agenda for [meeting type] with [participants]. Include time blocks and expected outcomes.", industry: "Universal"},
  { id: 72, category: "Business", title: "Concise executive summary (250 words)", text: "Write a concise executive summary (250 words) for this report: [paste report]. 3 key findings + recommended action.", industry: "Universal"},
  { id: 73, category: "Business", title: "90-day onboarding plan", text: "Create a 90-day onboarding plan for a new [job title]. Milestones for weeks 1, 2, 4, and month 3.", industry: "Universal"},
  { id: 74, category: "Business", title: "Project proposal for project", text: "Write a project proposal for [project]. Include objective, scope, deliverables, timeline, and success metrics.", industry: "Universal"},
  { id: 75, category: "Business", title: "OKRs for team/company for QX", text: "Draft OKRs for [team/company] for Q[X]. 3 Objectives, 3 Key Results each. Ambitious but achievable.", industry: "Universal"},
  { id: 76, category: "Business", title: "Change management communication plan", text: "Write a change management communication plan for [change]. Include stakeholder map, messaging, and timeline.", industry: "Universal"},
  { id: 77, category: "Business", title: "Risk register for project", text: "Create a risk register for [project]. 10 risks with: likelihood, impact, owner, and mitigation strategy.", industry: "Universal"},
  { id: 78, category: "HR & Recruiting", title: "Job description for job title", text: "Write a job description for [job title] at a [stage] company. Include responsibilities, requirements, and culture section.", industry: "Universal"},
  { id: 79, category: "HR & Recruiting", title: "Structured interview questions for role", text: "Create 10 structured interview questions for [role]. For each: competency tested, strong answer traits, follow-up probe.", industry: "Universal"},
  { id: 80, category: "HR & Recruiting", title: "Warm rejection email", text: "Write a warm rejection email for a final-round candidate for [role]. Leave the door open for future opportunities.", industry: "Universal"},
  { id: 81, category: "HR & Recruiting", title: "Balanced performance review for employee", text: "Draft a balanced performance review for [employee performance description]. Include strengths, growth areas, and 3 goals.", industry: "Universal"},
  { id: 82, category: "HR & Recruiting", title: "Team announcement email introducing new", text: "Write a team announcement email introducing new hire [name] joining as [role]. Friendly, include fun fact.", industry: "Universal"},
  { id: 83, category: "HR & Recruiting", title: "30-60-90 day onboarding plan", text: "Create a 30-60-90 day onboarding plan for a [role]. Clear milestones and success metrics for each phase.", industry: "Universal"},
  { id: 84, category: "HR & Recruiting", title: "Employee survey with 12 questions", text: "Write an employee survey with 12 questions on engagement, culture, and team satisfaction. 5-point scale + 2 open-ended.", industry: "Universal"},
  { id: 85, category: "HR & Recruiting", title: "Script for a difficult performance", text: "Draft a script for a difficult performance conversation with an employee who is underperforming in [area].", industry: "Universal"},
  { id: 86, category: "Productivity", title: "Tasks using the Eisenhower Matrix", text: "Prioritize these tasks using the Eisenhower Matrix: [list tasks]. Do / Schedule / Delegate / Drop.", industry: "Universal"},
  { id: 87, category: "Productivity", title: "Document in 5 bullet points", text: "Summarize this document in 5 bullet points and generate 3 follow-up action items: [paste document].", industry: "Universal"},
  { id: 88, category: "Productivity", title: "Prepare for a difficult conversation", text: "Help me prepare for a difficult conversation with [person] about [topic]. Structure my points + anticipate responses.", industry: "Universal"},
  { id: 89, category: "Productivity", title: "Weekly review template", text: "Create a weekly review template: progress assessment, blockers, next week priorities, and 3 reflection questions.", industry: "Universal"},
  { id: 90, category: "Productivity", title: "Daily planning prompt I can", text: "Write a daily planning prompt I can use each morning to set 3 priorities and identify one potential obstacle.", industry: "Universal"},
  { id: 91, category: "Productivity", title: "Meeting transcript into", text: "Turn this meeting transcript into: a 3-bullet summary, action items with owners, and a follow-up email: [paste transcript].", industry: "Universal"},
  { id: 92, category: "Productivity", title: "Step-by-step SOP for process", text: "Write a step-by-step SOP for [process]. Include decision points, responsible parties, and error handling.", industry: "Universal"},
  { id: 93, category: "Productivity", title: "Delegate this task to person", text: "Help me delegate this task to [person]. Write the delegation brief: context, outcome, resources, deadline, check-in.", industry: "Universal"},
  { id: 94, category: "Creative Writing", title: "The opening chapter (500 words)", text: "Write the opening chapter (500 words) of a [genre] novel. Protagonist: [character]. Setting: [setting]. Open with tension.", industry: "Universal"},
  { id: 95, category: "Creative Writing", title: "300-word story starting", text: "Write a 300-word story starting with: 'Nobody believed her until the lights went out.' End with an unexpected twist.", industry: "Universal"},
  { id: 96, category: "Creative Writing", title: "Paragraph in 4 styles", text: "Rewrite this paragraph in 4 styles: Hemingway, Dickens, modern blog, and academic: [paste paragraph].", industry: "Universal"},
  { id: 97, category: "Creative Writing", title: "Brand story for company using", text: "Write a brand story for [company] using the Hero's Journey. Customer = hero, company = guide. Include transformation.", industry: "Universal"},
  { id: 98, category: "Creative Writing", title: "Creative tagline options for brand", text: "Generate 10 creative tagline options for [brand]. Each max 6 words. Mix tone: bold, witty, emotional, minimalist.", industry: "Universal"},
  { id: 99, category: "Creative Writing", title: "3-minute spoken word script", text: "Write a 3-minute spoken word script about [topic] for a brand event. Poetic but professional. Ends on inspiration.", industry: "Universal"},
  { id: 100, category: "Creative Writing", title: "Character profiles for 3 buyer", text: "Create character profiles for 3 buyer personas of [brand]: name, age, job, pain points, goals, and ideal message.", industry: "Universal"},
  { id: 101, category: "E-Commerce", title: "SEO-optimized product titles", text: "Write 5 SEO-optimized product titles for an online store selling [product]. The titles should be descriptive, engaging, and between 50-60 characters.", industry: "Universal"},
  { id: 102, category: "E-Commerce", title: "Engaging cart abandonment email", text: "Create an engaging cart abandonment email for [brand/product]. Offer a [discount] incentive and use a witty tone.", industry: "Universal"},
  { id: 103, category: "E-Commerce", title: "Upsell email for customers who", text: "Write an upsell email for customers who recently purchased [product]. Introduce [upsell product] as the perfect complement.", industry: "Universal"},
  { id: 104, category: "E-Commerce", title: "Frequently Asked Questions (FAQ)", text: "Generate 10 Frequently Asked Questions (FAQ) with answers for a product page selling [product].", industry: "Universal"},
  { id: 105, category: "E-Commerce", title: "High-converting product description for product", text: "Write a high-converting product description for [product features]. Structure it with a problem, solution, bullet points, and a CTA.", industry: "Universal"},
  { id: 106, category: "E-Commerce", title: "Post-purchase review request email asking", text: "Draft a post-purchase review request email asking customers to leave a review for [product], offering a small reward for their time." , industry: "Universal"}
];

export const FAQS = [
  { question: "What are ChatGPT Prompts?", answer: "ChatGPT Prompts are structured instructions you give to ChatGPT to produce a specific output. A well-written ChatGPT Prompt includes a role definition, context, the desired format, and any constraints. The better the ChatGPT Prompt, the better the output — which is why using proven, pre-written ChatGPT Prompts consistently outperforms typing vague requests from scratch." },
  { question: "Are all the ChatGPT Prompts on this site really free?", answer: "Yes. Every ChatGPT Prompt on chatgpt-prompts.com is 100% free to copy and use — for personal and commercial purposes. There is no paywall, no account required, and no hidden fees. We believe everyone should have access to professional-grade ChatGPT Prompts without paying a subscription." },
  { question: "Do these ChatGPT Prompts work with GPT-4o, Claude, and Gemini?", answer: "Yes. All ChatGPT Prompts on this site are model-agnostic. They work with every major large language model including ChatGPT (GPT-3.5, GPT-4, GPT-4o), Claude (Anthropic), Gemini (Google), Mistral, and Llama. The better the model, the better the result — but every prompt produces useful output even on free-tier models." },
  { question: "How do I write better ChatGPT Prompts?", answer: "The four elements of a great ChatGPT Prompt are: (1) a role — tell ChatGPT who it is ('Act as a senior UX designer'), (2) context — give relevant background, (3) a task — state exactly what you need, and (4) format — specify the output structure (bullet points, table, email, etc.). Study the prompts on this site to see all four elements in action." },
  { question: "Can I use these ChatGPT Prompts for client work?", answer: "Absolutely. All ChatGPT Prompts on chatgpt-prompts.com are free for commercial use. Use them for your own business, for client projects, marketing agencies, sales teams, or internal training. No attribution required." },
  { question: "How often are new ChatGPT Prompts added?", answer: "We add new ChatGPT Prompts to the library every week. Categories are expanded based on user demand, emerging AI use cases, and professional feedback. Bookmark this page and return regularly to find new prompts across all categories." },
  { question: "What is the best ChatGPT Prompt for marketing?", answer: "There is no single 'best' ChatGPT Prompt for marketing — the right one depends on your goal. For campaign strategy, start with the full-funnel strategy prompt. For copy, use the value proposition or landing page prompts. For content planning, use the 30-day content calendar prompt. Browse the Marketing section for all 80+ options." },
  { question: "How do I customize a ChatGPT Prompt?", answer: "Every ChatGPT Prompt on this site uses [brackets] to mark the parts you should personalize. Replace [product] with your product name, [audience] with your target customer, [tone] with your brand voice, and so on. You can also add instructions after the prompt, such as 'Make it 50% shorter' or 'Add a statistic from the tech industry'." },
  { question: "What is the difference between a prompt and a template?", answer: "A ChatGPT Prompt is an instruction you give to an AI model. A template is a pre-written document with blank spaces to fill in. The ChatGPT Prompts on this site are more powerful than templates — instead of filling in a blank, you tell the AI what to create, and it generates content tailored to your specific context." },
  { question: "Can ChatGPT Prompts replace copywriters or marketers?", answer: "ChatGPT Prompts dramatically accelerate the work of copywriters, marketers, and other professionals — but they work best as a tool in the hands of a skilled person, not a replacement for one. The most effective use is to generate a strong first draft quickly, then apply human judgment, brand expertise, and strategic thinking to refine it." }
];
